name: Spotbugs Static Analysis

on:
  push:
    branches: 
      - 'spotbugs-ci'
      - 'main'
    tags: [v*]
  workflow_dispatch:

jobs:
  build_and_coverage_report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
      - name: Install test dependencies
        run: sudo apt-get -y -q --no-install-recommends install ffmpeg mediainfo tesseract-ocr tesseract-ocr-deu
      - name: Build with Maven
        run: mvn clean -DskipTests install 
      - name: Optionally configure Spotbugs
        run: mvn spotbugs:spotbugs
      - name: Run Spotbugs tests
        run: mvn spotbugs:check



     
